import { LaRosa, GPAA, ProjectThree, ProjectFour } from "../components/ProjectCard";

export const projects = [
    {
      id: '1',
      imgUrl: 'larosa',
      title: 'La Rosa',
      smallDesc: 'A Solange Urdang International dance and performance school',
      fullDesc: '',
      disciplineOne: '',
      disciplineTwo: '',
      disciplineThree: '',
      card: LaRosa,
    },
    {
      id: '2',
      imgUrl: 'gpaamain',
      title: 'GPAA',
      smallDesc: 'A Solange Urdang International dance and performance school',
      fullDesc: '',
      disciplineOne: '',
      disciplineTwo: '',
      disciplineThree: '',
      card: GPAA,
    },
    {
      id: '3',
      imgUrl: 'larosa',
      title: 'Project Three',
      smallDesc: 'A Solange Urdang International dance and performance school',
      fullDesc: '',
      disciplineOne: '',
      disciplineTwo: '',
      disciplineThree: '',
      card: ProjectThree,
    },
    {
      id: '4',
      imgUrl: 'larosa',
      title: 'Project Four',
      smallDesc: 'A Solange Urdang International dance and performance school',
      fullDesc: '',
      disciplineOne: '',
      disciplineTwo: '',
      disciplineThree: '',
      card: ProjectFour,
    },
  ];